// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZC1lhddNT6YkOK1Ec3Nx5jxuRKsRnL5E',
    appId: '1:244756230336:web:8d893dc4def97161dc3d25',
    messagingSenderId: '244756230336',
    projectId: 'smalld-e9eec',
    authDomain: 'smalld-e9eec.firebaseapp.com',
    databaseURL: 'https://smalld-e9eec.firebaseio.com',
    storageBucket: 'smalld-e9eec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxhOyGRbdt6xnj6KfhGJMyStEGaJ9v82Y',
    appId: '1:244756230336:android:c340004417437313dc3d25',
    messagingSenderId: '244756230336',
    projectId: 'smalld-e9eec',
    databaseURL: 'https://smalld-e9eec.firebaseio.com',
    storageBucket: 'smalld-e9eec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPkN0m9tttcAtyWENV87R4galtJzbOpdk',
    appId: '1:244756230336:ios:74e44d914f85e550dc3d25',
    messagingSenderId: '244756230336',
    projectId: 'smalld-e9eec',
    databaseURL: 'https://smalld-e9eec.firebaseio.com',
    storageBucket: 'smalld-e9eec.appspot.com',
    iosBundleId: 'com.example.theApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPkN0m9tttcAtyWENV87R4galtJzbOpdk',
    appId: '1:244756230336:ios:bd757c9d0792de86dc3d25',
    messagingSenderId: '244756230336',
    projectId: 'smalld-e9eec',
    databaseURL: 'https://smalld-e9eec.firebaseio.com',
    storageBucket: 'smalld-e9eec.appspot.com',
    iosBundleId: 'com.example.theApp.RunnerTests',
  );
}
